// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChannelItem struct {
	Title       string  `json:"title"`
	Duration    *string `json:"duration"`
	Description *string `json:"description"`
	URL         string  `json:"url"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type SearchItem struct {
	ID         int            `json:"id"`
	Artist     string         `json:"artist"`
	Track      string         `json:"track"`
	URL        string         `json:"url"`
	Country    *string        `json:"country"`
	Collection *string        `json:"collection"`
	FeedURL    *string        `json:"feedUrl"`
	Length     *int           `json:"length"`
	Feeds      []*ChannelItem `json:"feeds"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
